clear_cache:
  name: Clear Cache
  description: Clear the given cache type
  fields:
    cache_type:
      name: Cache Type
      description: The cache type that should be cleared
      required: true
      selector:
        select:
          options:
            - label: Authentication
              value: auth
            - label: Channels
              value: channels
            - label: Channel Listings
              value: listings
send_ircode:
  name: Send IR Code
  description: Send the given IR code to the media player
  target:
    entity:
      domain: media_player
      integration: virginmedia_tv
  fields:
    code:
      name: IR Code
      description: The IR code to send to the device
      required: true
      example: "pause"
      selector:
        select:
          options:
            !include codes/common_codes.yaml
send_keycode:
  name: Send Key Code
  description: Send the given key code to the media player
  target:
    entity:
      domain: media_player
      integration: virginmedia_tv
  fields:
    code:
      name: Key Code
      description: The key code to send to the device
      required: true
      example: "num0"
      selector:
        select:
          options:
            !include_dir_merge_list codes
update_channels:
  name: Update Channels
  description: Force update the channel cache. This is useful if there has been channel changes before configured re-cache time.
               This will only update the selected entity. Other entities will update when they next change channel.
  target:
    entity:
      domain: media_player
      integration: virginmedia_tv
